[options]
; Master password untuk database manager
admin_passwd = paul

; Database connection
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

; Folder addons
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

; Logging level (opsional)
log_level = info
logfile = /var/log/odoo/odoo.log
